# Generated by Django 4.1.13 on 2023-11-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_post_rename_location_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='write_post',
        ),
    ]
