# Generated by Django 4.1.13 on 2023-11-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_broadcast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadcast',
            old_name='write_post',
            new_name='broadcast',
        ),
    ]
