# Generated by Django 4.1.13 on 2023-11-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_rename_write_post_broadcast_broadcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
